title: My Programming Blog
description: A blog about my programming journey
baseurl: "" # リポジトリ名が "your-username.github.io" の場合は空にします
url: "https://your-username.github.io"
theme: minima
collections:
  pages:
    output: true
    permalink: /:path/
