title: My Programming Blog
description: A blog about my programming journey
baseurl: "/test" # リポジトリ名に一致
url: "https://your-username.github.io"
theme: minima
collections:
  pages:
    output: true
    permalink: /:path/

